### ISSUE TITLE
What can we do for the publice into Google Play Store about this project?

### ISSUE THREAD

**Issue by Tanvirul-cse** [HarshAndroid/FreeVPN-App-Flutter#20]
Please share possible to how we can prepare this project for publiced

**Comment by HarshAndroid** [comment]
Actually I also tried upgrading this project to latest OpenVPN SDK but then it was not connecting with free servers from VPN Gate.

So I had to reverse the changes.

**Comment by Tanvirul-cse** [comment]
> Actually I also tried upgrading this project to latest OpenVPN SDK but then it was not connecting with free servers from VPN Gate.
> 
> So I had to reverse the changes.

So, does that mean it's not gonna reject from the google Play Store?

**Comment by HarshAndroid** [comment]
Yes.

I will recommend you to research about wireguard protocol and servers, if you want to create your own vpn app and publish it on playstore (but it will not be completely free).

**Comment by Tanvirul-cse** [comment]
> Yes.
> 
> I will recommend you to research about wireguard protocol and servers, if you want to create your own vpn app and publish it on playstore (but it will not be completely free).

Thank you so much for your suggestion .
