### ISSUE TITLE
your project is outdated 

### ISSUE THREAD

**Issue by hostworldly** [HarshAndroid/FreeVPN-App-Flutter#6]
i'm your viewers i tried with latest version of flutter but your outdated
i'm learns and begins to flutter 

looking for a new video for new flutter lib

https://pub.dev/packages/openvpn_sf_flutter/

help me us!

**Comment by HarshAndroid** [comment]
Actually at the course creation time this package was not available and if it is really working as you would say then you can just pass username & password and ovpn key and connect using this package. I've covered the basics of it in this course, means what you needed to do to connect to ovpn protocol.

**Comment by ahwazi12** [comment]
Hi how are you The software you made cannot be logged in by BIOS password and support the v2ray protocol If you do the project for me, I will be very grateful. We can communicate on Telegram @ahvaz_gsm
