### ISSUE TITLE
How using "private key password"?

### ISSUE THREAD

**Issue by FetFrumos** [HarshAndroid/FreeVPN-App-Flutter#8]
hi Author, thank you for a great app.
I'm running my own server with some configuration quirks. I need to use "private key password",  but I didn't find that option. can you help me?  thank you

**Comment by HarshAndroid** [comment]
First of all thanks for compliment.
And regarding private key password, actually I also don't know much regarding it.

And if current configuration are not working for you in this project then try once checking below package too (may be it can be helpful to you): https://pub.dev/packages/openvpn_sf_flutter

**Comment by ahwazi12** [comment]
Hi how are you The software you made cannot be logged in by BIOS password and support the v2ray protocol If you do the project for me, I will be very grateful. We can communicate on Telegram @ahvaz_gsm

**Comment by ahwazi12** [comment]
![IMG_20240104_184720_362](https://github.com/HarshAndroid/FreeVPN-App-Flutter/assets/119062798/74457e03-6be3-418b-a8cd-0bbbc9e55fcb)
![IMG_20240104_184720_425](https://github.com/HarshAndroid/FreeVPN-App-Flutter/assets/119062798/674059d5-11df-43df-984f-6244f178a6ec)
